Updated basic workflow.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -204,7 +204,7 @@ cmd_start() {
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || echo "Unable to fetch from $ORIGIN."
 	fi
 
 	# if the origin branch counterpart exists, assert that the local branch
@@ -285,7 +285,7 @@ cmd_finish() {
 	# update local repo with remote changes first, if asked
 	if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
 		if flag fetch; then
-			git fetch -q "$ORIGIN" "$BRANCH"
+			git fetch -q "$ORIGIN" "$BRANCH" || echo "Unable to fetch from $ORIGIN."
 		fi
 	fi
 
@@ -344,7 +344,10 @@ helper_finish_cleanup() {
 
 	# delete branch
 	if flag fetch; then
-		git push "$ORIGIN" ":refs/heads/$BRANCH"
+
+	    if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
+		    git push "$ORIGIN" ":refs/heads/$BRANCH" || echo "Unable to delete $BRANCH from $ORIGIN."
+        fi
 	fi
 	
 	
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -162,7 +162,7 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || echo "Unable to fetch from $ORIGIN"
 	fi
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -207,9 +207,9 @@ cmd_finish() {
 	require_clean_working_tree
 	if flag fetch; then
 		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		  echo "Could not fetch $MASTER_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+		  echo "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
 	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
@@ -267,16 +267,16 @@ cmd_finish() {
 
 	if flag push; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+			echo "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+			echo "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git push "$ORIGIN" "$tagname" || \
-			  die "Could not push tags to $ORIGIN."
+			  echo "Could not push tags to $ORIGIN."
 		fi
 	    if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
 		    git push "$ORIGIN" :"$BRANCH" || \
-			    die "Could not delete the remote $BRANCH in $ORIGIN."
+			    echo "Could not delete the remote $BRANCH in $ORIGIN."
         fi
 	fi
 
